"use strict";

function lessonThree(){
 const saved=id=>esc(state.answers[id]||"");
 const selected=(key,value)=>state.choices[key]?.includes(value)?"selected":"";
 const solo='<span class="activity-label solo">✍️ DO IT YOURSELF</span>';
 const talk=(title,body)=>`<aside class="one-to-one-prompt"><strong>🗣 ${title}</strong>${body}</aside>`;
 const firstQuestions=["What's your name?","Where are you from?","What do you like doing?","Have you got any brothers or sisters?","What's your favourite school subject?","How much money do your parents make?","Why did your parents argue yesterday?","What's your phone password?"];
 const boundaries={"Where are you from?":"OK TO ASK","What do you do in your free time?":"OK TO ASK","Have you got any brothers or sisters?":"OK TO ASK","What music do you like?":"OK TO ASK","Where exactly do you live?":"MAYBE LATER","How much money does your family have?":"TOO PERSONAL","Are your parents married?":"TOO PERSONAL","What's your phone number?":"MAYBE LATER","What school do you go to?":"OK TO ASK","What are you worried about at the moment?":"MAYBE LATER"};
 const families={"Where are you from?":"BE","What do you usually do after school?":"DO","Have you got any pets?":"HAVE","What is your favourite subject?":"BE","Have you been here before?":"HAVE","What kind of music do you like?":"DO"};
 const fixes=[
  {prompt:"Where you are from?",options:["Where are you from?","Where do you from?","From where you are?"],correct:"Where are you from?"},
  {prompt:"What do you favourite subject?",options:["What does your favourite subject?","What is your favourite subject?","What your favourite subject is?"],correct:"What is your favourite subject?"},
  {prompt:"Have you any brothers?",options:["Do you got any brothers?","Have you got any brothers?","Are you have any brothers?"],correct:"Have you got any brothers?"},
  {prompt:"What you like doing?",options:["What do you like doing?","What are you like doing?","What does you like doing?"],correct:"What do you like doing?"},
  {prompt:"Where do you from?",options:["Where have you from?","Where are you from?","Where you do from?"],correct:"Where are you from?"}
 ];
 const build=[
  {words:["your","what","name","is"],correct:"What is your name?"},{words:["from","where","you","are"],correct:"Where are you from?"},{words:["brothers","got","you","any","have","or","sisters"],correct:"Have you got any brothers or sisters?"},{words:["doing","what","like","you","do"],correct:"What do you like doing?"},{words:["subject","favourite","your","what's"],correct:"What's your favourite subject?"},{words:["here","been","before","you","have"],correct:"Have you been here before?"}
 ];
 const buildCards=build.map((q,i)=>`<div class="question-builder" data-build="${i}" data-correct="${esc(q.correct)}"><strong>${i+1}</strong><div class="build-answer">${(state.choices.l3_build?.[i]||[]).map(w=>`<button data-built-word="${esc(w)}">${w}</button>`).join("")}</div><div class="word-chips">${q.words.map(w=>`<button class="word-chip" data-word="${esc(w)}">${w}</button>`).join("")}</div><div class="button-row"><button class="btn reset-build">Reset</button><button class="btn primary check-build">Check</button></div><p class="feedback">${state.scores[`l3_build_${i}`]===1?`✓ ${q.correct}`:""}</p></div>`).join("");
 const expanded=["Where are you from?","What do you like doing?","Have you got any brothers or sisters?","What's your favourite school subject?"];
 const frames=["I'm from ______. It's ______.","I like ______ because ______.","Yes, I have. I've got ______. We usually ______ together. / No, I haven't.","My favourite subject is ______ because ______."];
 const followAnswers=["I play volleyball.","I've got a younger brother.","I love fantasy books.","My favourite subject is biology."];
 const profileFields=["My name","I'm from","My family","I like","I'm interested in","My favourite…","One interesting thing about me"];
 const interview=["I greeted the teacher.","I answered at least 4 questions.","I added a detail in at least 3 answers.","I asked the teacher 2 questions.","I used at least 1 follow-up question.","I reacted naturally."];
 const questionBank=["What do you usually do after school?","What kind of music do you like?","Have you got any brothers or sisters?","What's your favourite place in your town?","What are you really interested in?","What school subject do you like most?","What do you usually do at weekends?","Have you ever joined a new club?","What would you like to learn this year?","What makes you laugh?","What kind of books or films do you like?","What is something you are good at?"];
 return `<div class="lesson-three">
 <header class="l3-hero"><div><p class="eyebrow">Week 2 · Lesson 3</p><h1>Giving Personal<br>Information</h1><p class="subtitle">Listening · Speaking · Functional Language</p><div class="l3-goal"><strong>Today I can…</strong><span>ask for and give personal information and keep a short conversation going.</span><small>I can give more than a one-word answer and ask a follow-up question. <b>≈ 60 min</b></small></div></div><figure><img src="assets/lesson-3/lesson-3-hero.png" alt="Two teenagers getting to know each other at an English club"><figcaption>A good conversation is a two-way street.</figcaption></figure></header>
 <nav class="l3-tabs">${[["first","💗 First Impressions"],["questions","💚 Question Lab"],["listening","💙 Listening"],["conversation","💜 Conversation Lab"],["profile","💛 My Profile Challenge"]].map(([id,t])=>`<button class="l3-tab" data-l3-section="${id}">${t}</button>`).join("")}</nav>

 <section class="l3-section" data-l3-panel="first"><div class="section-heading"><span>8–10 min</span><h2>First Impressions</h2></div>
 <article class="task l3-task first-ask">${solo}<span class="task-number">TASK 1 · WHAT WOULD YOU ASK?</span><h2>Which THREE questions would you ask first?</h2><div class="first-meeting-context"><img src="assets/lesson-3/first-meeting.png" alt="Two teenagers who have just met"><p>You meet someone your age for the first time at an English club.</p></div><div class="question-card-grid">${firstQuestions.map(q=>`<button class="question-card ${selected("l3_first_questions",q)}" data-l3-pick="l3_first_questions" data-value="${esc(q)}" data-max="3">${q}</button>`).join("")}</div><button class="btn primary save-l3-picks" data-key="l3_first_questions" data-message="Good start. Now think about why some questions feel more natural than others.">Save my questions</button><p class="feedback"></p>${talk("TALK TO YOUR TEACHER",'<p>Explain why you chose one of your questions.</p><p class="sentence-frame">I chose this question because…</p>')}</article>
 ${selectTask("l3_boundaries",2,"Is it OK to ask?","Classify each question. Social rules depend on context.",Object.entries(boundaries).map(([label,correct])=>({label,correct})),["OK TO ASK","MAYBE LATER","TOO PERSONAL"],true,"Context matters. Some questions may be fine once you know someone better.").replace('<article class="card task','<article class="card task l3-task').replace('</article>',`${talk("TALK TO YOUR TEACHER",'<p>Choose ONE question from “Maybe Later”. When could it be OK to ask it?</p>')}</article>`)}
 <div class="section-nav"><button class="btn l3-next" data-go="questions">Next: Question Lab →</button></div></section>

 <section class="l3-section" data-l3-panel="questions"><div class="section-heading"><span>13–15 min</span><h2>Question Lab</h2></div>
 <article class="task l3-task build-task">${solo}<span class="task-number">TASK 3 · BUILD THE QUESTION</span><h2>Put the words in order</h2><p>Click the words to build each question.</p>${buildCards}</article>
 ${selectTask("l3_families",4,"Which question pattern is it?","Choose BE, DO or HAVE.",Object.entries(families).map(([label,correct])=>({label,correct})),["BE","DO","HAVE"],true).replace('<article class="card task','<article class="card task l3-task').replace('<p>Choose BE, DO or HAVE.</p>','<p>Choose BE, DO or HAVE.</p><div class="family-guide"><p><b>BE</b><span>Where <em>are</em> you from?</span></p><p><b>DO</b><span>What <em>do</em> you like doing?</span></p><p><b>HAVE</b><span><em>Have</em> you got any pets?</span></p></div>')}
 ${mcTask("l3_fix",5,"Something is wrong…","Choose the corrected question.",fixes,"Check").replace('<article class="card task','<article class="card task l3-task').replace('</article>',`${talk("QUICK TEACHER CHECK",'<p>Correct two questions your teacher says orally.</p><small>Teacher prompts: “What you usually do at weekends?” · “Have you got brother?”</small>')}</article>`)}
 <div class="section-nav"><button class="btn l3-next" data-go="first">← Previous</button><button class="btn l3-next" data-go="listening">Next: Listening →</button></div></section>

 <section class="l3-section" data-l3-panel="listening"><div class="section-heading"><span>10–12 min</span><h2>Listening</h2></div><aside class="audio-note">🎧 Use the Spotlight audio for <strong>Module 1b</strong>.</aside>
 <article class="task l3-task">${solo}<span class="task-number">TASK 6 · BEFORE YOU LISTEN</span><h2>What information do you expect to hear?</h2><p>Choose up to FIVE.</p><div class="chip-grid">${["name","age","family","favourite food","hometown","interests","school subject","full home address","phone password"].map(x=>`<button class="journal-chip ${selected("l3_listen_prediction",x)}" data-l3-pick="l3_listen_prediction" data-value="${x}" data-max="5">${x}</button>`).join("")}</div><button class="btn primary save-l3-picks" data-key="l3_listen_prediction" data-message="Listen once and check what kind of information you actually hear.">Save prediction</button><p class="feedback"></p></article>
 <article class="task l3-task first-listen">${solo}<span class="task-number">TASK 7 · LISTEN FOR THE BASICS</span><h2>First listen</h2><p>Don't try to understand every word. Listen for the basic information.</p><div class="listen-table"><span></span>${["Name","Place","Family","Interest"].map(x=>`<b>${x}</b>`).join("")}${[0,1,2].map(p=>`<strong>Person ${p+1}</strong>${[0,1,2,3].map(f=>`<label><input type="checkbox" data-first-listen="${p}-${f}" ${state.choices.l3_first_listen?.includes(`${p}-${f}`)?"checked":""}><span>heard</span></label>`).join("")}`).join("")}</div><button class="btn primary save-first-listen">Save first listen</button><p class="feedback"></p></article>
 <article class="task l3-task listen-detail">${solo}<span class="task-number">TASK 8 · LISTEN FOR DETAIL</span><h2>Second listen</h2>${[0,1,2].map(i=>`<label>Person ${i+1}<input id="l3_detail_${i}" value="${saved(`l3_detail_${i}`)}" placeholder="One detail I heard…"></label>`).join("")}<h3>What helped you catch the information?</h3><div class="chip-grid compact">${["a name","a number","a place","a family word","an activity","tone of voice"].map(x=>`<button class="journal-chip ${selected("l3_listen_clues",x)}" data-l3-pick="l3_listen_clues" data-value="${x}" data-max="6">${x}</button>`).join("")}</div><button class="btn primary save-listen-detail">Save answers</button><p class="feedback"></p><p class="strategy">Good listeners listen for key information instead of trying to translate every word.</p>${talk("TALK TO YOUR TEACHER",'<p>Which information was easiest to catch? Which was harder? What clue helped you most?</p>')}</article>
 <div class="section-nav"><button class="btn l3-next" data-go="questions">← Previous</button><button class="btn l3-next" data-go="conversation">Next: Conversation Lab →</button></div></section>

 <section class="l3-section" data-l3-panel="conversation"><div class="section-heading"><span>12–14 min</span><h2>Conversation Lab</h2></div>
 <article class="task l3-task expanded-task">${solo}<span class="task-number">TASK 9 · SHORT ANSWER → BETTER ANSWER</span><h2>Don't stop after one word</h2><div class="answer-upgrade"><p><b>TOO SHORT</b>English.</p><p><b>BETTER</b>My favourite subject is English because I like reading and learning new words.</p></div>${expanded.map((q,i)=>`<label><strong>${i+1}. ${q}</strong><small>${frames[i]}</small><textarea id="l3_expanded_${i}">${saved(`l3_expanded_${i}`)}</textarea></label>`).join("")}<button class="btn primary save-expanded">Save my answers</button><p class="feedback"></p></article>
 <article class="task l3-task follow-task">${solo}<span class="task-number">TASK 10 · FOLLOW-UP QUESTION</span><h2>Keep the conversation alive</h2><div class="follow-examples"><p>I love drawing. <b>→ What do you usually draw?</b></p><p>I'm from Kazan. <b>→ Do you like living there?</b></p></div>${followAnswers.map((a,i)=>`<label><strong>${i+1}. ${a}</strong><input id="l3_follow_${i}" value="${saved(`l3_follow_${i}`)}" placeholder="Write one natural follow-up question…"></label>`).join("")}<button class="btn primary save-follow">Save questions</button><p class="feedback"></p>${talk("TALK TO YOUR TEACHER",'<p>Your teacher chooses one follow-up question and answers it. React naturally.</p>')}</article>
 <article class="task l3-task formula-task"><span class="task-number">TASK 11 · CONVERSATION FORMULA</span><h2>How does a conversation keep going?</h2><img src="assets/lesson-3/conversation-lab.png" alt="Two teenagers keeping a friendly conversation going"><div class="conversation-formula">${["ASK","ANSWER","ADD A DETAIL","REACT","FOLLOW UP"].map((x,i)=>`<span>${x}</span>${i<4?"<i>↓</i>":""}`).join("")}</div><blockquote>A: Where are you from?<br>B: I'm from Samara. It's a big city.<br>A: Oh, cool! Do you like living there?</blockquote>${talk("TALK TO YOUR TEACHER",'<p>Your teacher starts: “What do you like doing in your free time?”</p><p>Answer, add one detail, react and ask one question back.</p>')}<div class="self-check">${["I answered.","I added a detail.","I asked something back."].map((x,i)=>`<label><input type="checkbox" data-conversation-check="${i}" ${state.choices.l3_conversation_check?.[i]?"checked":""}> ${x}</label>`).join("")}</div></article>
 <div class="section-nav"><button class="btn l3-next" data-go="listening">← Previous</button><button class="btn l3-next" data-go="profile">Next: My Profile →</button></div></section>

 <section class="l3-section" data-l3-panel="profile"><div class="section-heading"><span>10–12 min</span><h2>My Profile Challenge</h2></div>
 <article class="task l3-task profile-card-task">${solo}<span class="task-number">TASK 12 · MY PROFILE CARD</span><h2>A little about me</h2><p class="privacy-note">🔒 You can skip any information you don't want to share.</p><div class="profile-fields">${profileFields.map((x,i)=>`<label>${x}<input id="l3_profile_${i}" value="${saved(`l3_profile_${i}`)}"></label>`).join("")}</div><button class="btn primary save-l3-profile">Save profile</button><p class="feedback"></p></article>
 <article class="task l3-task interview-task"><span class="activity-label talk">🗣 TALK TO YOUR TEACHER</span><span class="task-number">TASK 13 · TEACHER INTERVIEW</span><h2>Your first conversation at a new English club</h2><p>Your teacher begins: <b>“Hi! I'm … Nice to meet you.”</b></p><div class="phrase-bank"><div><b>REACT</b><span>Really? · Me too! · That's interesting. · Oh, I see. · That sounds fun.</span></div><div><b>ASK BACK</b><span>What about you? · And you? · How about you?</span></div><div><b>FOLLOW UP</b><span>Why? · How often? · What kind of…? · Do you like…? · When did you…?</span></div></div><div class="interview-checks">${interview.map((x,i)=>`<label><input type="checkbox" data-interview-check="${i}" ${state.choices.l3_interview?.[i]?"checked":""}> ${x}</label>`).join("")}</div></article>
 <article class="task l3-task generator-task"><span class="activity-label talk">🗣 TALK TO YOUR TEACHER</span><span class="task-number">TASK 14 · QUESTION GENERATOR</span><h2>🎲 Give me a question</h2><div class="generated-question">${esc(state.answers.l3_last_question||"Press the button when you're ready.")}</div><div class="button-row"><button class="btn primary generate-question">${state.answers.l3_last_question?"Another question":"Give me a question"}</button><button class="btn answered-question">I answered it ✓</button></div><p><strong data-answer-count>${Number(state.answers.l3_answer_count||0)}</strong> answered this session</p></article>
 <article class="task l3-task exit-ticket">${solo}<span class="task-number">TASK 15 · EXIT TICKET</span><h2>Before you go…</h2><label>One question I can now ask easily:<input id="l3_exit_question" value="${saved("l3_exit_question")}"></label><label>One useful phrase I used today:<input id="l3_exit_phrase" value="${saved("l3_exit_phrase")}"></label><h3>My answers today were…</h3><div class="question-card-grid answer-levels">${[["one","🔴 mostly one sentence"],["detail","🟡 usually answer + detail"],["full","🟢 answer + detail + question back"]].map(([v,t])=>`<button class="question-card ${selected("l3_answer_level",v)}" data-l3-pick="l3_answer_level" data-value="${v}" data-max="1">${t}</button>`).join("")}</div><h3>I can now…</h3><div class="exit-checks">${["ask for personal information","give a longer answer","ask a follow-up question","keep a short conversation going"].map((x,i)=>`<label><input type="checkbox" data-exit-check="${i}" ${state.choices.l3_exit_checks?.[i]?"checked":""}> ${x}</label>`).join("")}</div><button class="btn primary finish-l3">Finish Lesson</button><div class="finish-message" hidden><h3>Lesson complete! ✨</h3><p>You can now ask, answer and keep the conversation going.</p><div class="button-row"><button class="btn l3-prev">← Previous Lesson</button><button class="btn go-module">Back to Module</button><button class="btn primary l3-next-lesson">Next Lesson →</button></div></div></article>
 <div class="section-nav"><button class="btn l3-next" data-go="conversation">← Previous</button></div></section></div>`;
}

function bindLessonThree(){
 const sections=["first","questions","listening","conversation","profile"];
 const show=name=>{app.querySelectorAll(".l3-section").forEach(x=>x.classList.toggle("active",x.dataset.l3Panel===name));app.querySelectorAll(".l3-tab").forEach(x=>x.classList.toggle("active",x.dataset.l3Section===name));state.answers.l3_tab=name;saveState();window.scrollTo(0,0)};
 const requested=new URLSearchParams(location.search).get("section");show(sections.includes(requested)?requested:(state.answers.l3_tab||"first"));
 app.querySelectorAll(".l3-tab,.l3-next").forEach(b=>b.onclick=()=>show(b.dataset.l3Section||b.dataset.go));
 app.querySelectorAll("[data-l3-pick]").forEach(b=>b.onclick=()=>{const key=b.dataset.l3Pick,value=b.dataset.value,max=Number(b.dataset.max),current=state.choices[key]||[];if(current.includes(value))state.choices[key]=current.filter(x=>x!==value);else if(current.length<max)state.choices[key]=[...current,value];else if(max===1)state.choices[key]=[value];else return toast(`Choose up to ${max}`);saveState();app.querySelectorAll(`[data-l3-pick="${key}"]`).forEach(x=>x.classList.toggle("selected",state.choices[key].includes(x.dataset.value)))});
 app.querySelectorAll(".save-l3-picks").forEach(b=>b.onclick=()=>{saveState();b.nextElementSibling.textContent=b.dataset.message||"Saved ✓"});
 app.querySelectorAll(".question-builder").forEach(box=>{const i=Number(box.dataset.build),answer=box.querySelector(".build-answer"),sync=()=>{state.choices.l3_build=state.choices.l3_build||[];state.choices.l3_build[i]=[...answer.querySelectorAll("button")].map(x=>x.dataset.builtWord);saveState()};box.querySelectorAll(".word-chip").forEach(b=>b.onclick=()=>{const built=document.createElement("button");built.dataset.builtWord=b.dataset.word;built.textContent=b.dataset.word;built.onclick=()=>{built.remove();sync()};answer.append(built);sync()});answer.querySelectorAll("button").forEach(b=>b.onclick=()=>{b.remove();sync()});box.querySelector(".reset-build").onclick=()=>{answer.innerHTML="";sync();box.querySelector(".feedback").textContent=""};box.querySelector(".check-build").onclick=()=>{const words=[...answer.querySelectorAll("button")].map(x=>x.dataset.builtWord),sentence=words.join(" ").replace(/^./,c=>c.toUpperCase())+"?",ok=sentence.toLowerCase()===box.dataset.correct.toLowerCase();state.scores[`l3_build_${i}`]=ok?1:0;saveState();box.querySelector(".feedback").textContent=ok?`✓ ${box.dataset.correct}`:"Not quite. Change the word order and try again."}});
 app.querySelector(".save-first-listen")?.addEventListener("click",e=>{state.choices.l3_first_listen=[...app.querySelectorAll("[data-first-listen]:checked")].map(x=>x.dataset.firstListen);saveState();e.currentTarget.nextElementSibling.textContent="First listen saved ✓"});
 app.querySelector(".save-listen-detail")?.addEventListener("click",e=>{[0,1,2].forEach(i=>state.answers[`l3_detail_${i}`]=document.getElementById(`l3_detail_${i}`).value.trim());saveState();e.currentTarget.nextElementSibling.textContent="Listening notes saved ✓"});
 const saveFields=(prefix,count,feedback)=>{for(let i=0;i<count;i++){const el=document.getElementById(`${prefix}_${i}`);if(el)state.answers[`${prefix}_${i}`]=el.value.trim()}saveState();if(feedback)feedback.textContent="Saved ✓"};
 app.querySelector(".save-expanded")?.addEventListener("click",e=>saveFields("l3_expanded",4,e.currentTarget.nextElementSibling));app.querySelector(".save-follow")?.addEventListener("click",e=>saveFields("l3_follow",4,e.currentTarget.nextElementSibling));app.querySelector(".save-l3-profile")?.addEventListener("click",e=>saveFields("l3_profile",7,e.currentTarget.nextElementSibling));
 app.querySelectorAll("[data-conversation-check]").forEach(c=>c.onchange=()=>{state.choices.l3_conversation_check=[...app.querySelectorAll("[data-conversation-check]")].map(x=>x.checked);saveState()});app.querySelectorAll("[data-interview-check]").forEach(c=>c.onchange=()=>{state.choices.l3_interview=[...app.querySelectorAll("[data-interview-check]")].map(x=>x.checked);saveState()});app.querySelectorAll("[data-exit-check]").forEach(c=>c.onchange=()=>{state.choices.l3_exit_checks=[...app.querySelectorAll("[data-exit-check]")].map(x=>x.checked);saveState()});
 const bank=["What do you usually do after school?","What kind of music do you like?","Have you got any brothers or sisters?","What's your favourite place in your town?","What are you really interested in?","What school subject do you like most?","What do you usually do at weekends?","Have you ever joined a new club?","What would you like to learn this year?","What makes you laugh?","What kind of books or films do you like?","What is something you are good at?"];
 app.querySelector(".generate-question")?.addEventListener("click",e=>{let next;do next=bank[Math.floor(Math.random()*bank.length)];while(bank.length>1&&next===state.answers.l3_last_question);state.answers.l3_last_question=next;saveState();app.querySelector(".generated-question").textContent=next;e.currentTarget.textContent="Another question"});app.querySelector(".answered-question")?.addEventListener("click",()=>{state.answers.l3_answer_count=Number(state.answers.l3_answer_count||0)+1;saveState();app.querySelector("[data-answer-count]").textContent=state.answers.l3_answer_count});
 app.querySelector(".finish-l3")?.addEventListener("click",e=>{app.querySelectorAll('input[id^="l3_"],textarea[id^="l3_"]').forEach(el=>state.answers[el.id]=el.value.trim());state.choices.l3_first_listen=[...app.querySelectorAll("[data-first-listen]:checked")].map(x=>x.dataset.firstListen);state.choices.l3_conversation_check=[...app.querySelectorAll("[data-conversation-check]")].map(x=>x.checked);state.choices.l3_interview=[...app.querySelectorAll("[data-interview-check]")].map(x=>x.checked);state.choices.l3_exit_checks=[...app.querySelectorAll("[data-exit-check]")].map(x=>x.checked);if(!state.done.includes(3))state.done.push(3);state.done.sort((a,b)=>a-b);const checks=state.choices.l3_interview||[];if(checks[1]&&checks[3]&&checks[4])state.achievements.conversationStarter=true;saveState();e.currentTarget.nextElementSibling.hidden=false;toast("Lesson 3 complete! ✨")});
 app.querySelector(".l3-prev")?.addEventListener("click",()=>navigate("lesson",2));app.querySelector(".go-module")?.addEventListener("click",()=>navigate("module"));app.querySelector(".l3-next-lesson")?.addEventListener("click",()=>navigate("lesson",4));
}
