"use strict";

function lessonOneGuidedReading(saved,chip){
 const core='<span class="spotlight-core">📘 SPOTLIGHT CORE</span>';
 const mc=(id,title,text,items)=>mcTask(id,'',title,text,items,'Check').replace('<span class="task-number">TASK </span>','').replace('<article class="card task','<article class="card task guided-mini');
 const cont=(next,label='Continue reading →')=>`<div class="read-actions"><button class="btn primary read-continue" data-next-read="${next}">${label}</button><button class="text-button read-anyway" data-next-read="${next}">Continue anyway</button></div>`;
 const card=(n,title,icon,text,task,next,label)=>`<article class="reading-step" data-read-step="${n}"><div class="read-step-head"><span>READ ${n}</span><small>Paragraph ${n} of 8</small></div><h2>${icon||''} ${title}</h2><div class="paragraph-copy">${text}</div><div class="check-it"><b>CHECK IT</b>${task}</div>${cont(next,label)}</article>`;
 const p1=`<p>The new girl in your class seems very interesting and you would like to get to know her better. The guy at the skate park does some amazing tricks and you would like him to show you how. But, whenever the opportunity to talk to them <mark>comes up</mark>, you can't think of anything to say. Your <mark>palms sweat</mark>, you <mark>blush</mark>, and you <mark>look away</mark>.</p><figure class="reading-insert reading-insert-problem editorial-image"><img src="assets/lesson-1/vocab-awkward.png" alt="Two teenagers feeling awkward before starting a conversation" loading="lazy"><figcaption>First meetings can feel awkward.</figcaption></figure>`;
 const p2=`<p>Whether you are starting a new school, going to a party where you don't know anyone or want to approach a person you fancy, you often need to break the ice in order to start a friendly conversation. Breaking the ice means saying or doing something to stop feeling shy or uncomfortable around someone you don't know very well. The reason you feel this way is that you don't know how the other person will react, but don't let it get you down.</p>`;
 const p3=`<p>You shouldn't worry. Almost everyone feels uncomfortable when they first meet other people. If you feel this way, the following tips can help you out.</p>`;
 const p4=`<div><h3>Smile</h3><p>When you smile, people think you are friendly and easy to talk to. They are also very likely to smile back and help you feel more comfortable about starting a conversation.</p></div><figure class="reading-insert reading-insert-smile editorial-image"><img src="assets/lesson-1/ice-situation-b.png" alt="Teenager smiling and starting a friendly conversation" loading="lazy"><figcaption>Start small.</figcaption></figure>`;
 const p5=`<h3>Develop passions</h3><p>The best way to have interesting conversations is to be an interesting person! Get involved in activities and talk about them. Make sure you have something to add to a conversation.</p>`;
 const p6=`<h3>Be positive</h3><p>Everybody likes to be around happy people. Try to always look on the bright side of life and to see something positive even in negative situations. People will enjoy your positive energy and benefit from it. Also, be confident. If you like yourself, others will probably like you too.</p>`;
 const p7=`<h3>Be a good listener</h3><p>Develop listening skills. Don't take over the conversation and don't only speak about yourself. Ask other people questions about themselves too. This way they'll know you're interested in them.</p>`;
 const p8=`<h3>Get out there</h3><p>Don't avoid being around new people just because you feel uncomfortable. If you stay in a situation, you'll get used to it. It's not easy, but it's worth it. After all, the other person may want to talk to you as well — but be too shy to break the ice!</p>`;
 const tfd=[['Breaking the ice means saying or doing something to start feeling relaxed with a new person.','T'],["People feel uncomfortable when meeting someone new because they cannot predict their reactions.",'T'],["Some people don't have any passions.",'DS'],["When you meet someone for the first time, it's better to look serious.",'F'],["Confident people don't postpone things.",'DS'],['When you start a conversation, talk a lot about yourself.','F'],['If you feel uncomfortable with new people, avoid being around them.','F']];
 const corrections={3:'Smiling can help you look friendly and easy to talk to.',5:"Don't talk only about yourself. Ask the other person questions too.",6:"Don't avoid being around new people; give yourself opportunities to get used to the situation."};
 const words=[['come up','happen / appear as an opportunity',['happen / appear as an opportunity','fall down','finish']],['blush','become red in the face',['become red in the face','smile','become angry']],['break the ice','make a first meeting feel easier',['make a first meeting feel easier','break something cold','end a friendship']],['react','do or say something in response',['do or say something in response','change appearance','go somewhere']],['get somebody down','make somebody feel unhappy',['make somebody feel unhappy','help somebody stand','invite somebody out']],['help somebody out','help somebody with a difficulty',['help somebody with a difficulty','ask for money','leave somebody alone']],['benefit from','get something useful from',['get something useful from','disagree with','lose interest in']],['take over','control most of the conversation yourself',['control most of the conversation yourself','leave the conversation','change the language']],['avoid','stay away from',['stay away from','move closer to','trust immediately']],['get used to','become more comfortable or familiar over time',['become more comfortable or familiar over time','forget completely','stop doing']],['worth it','good enough to justify the effort',['good enough to justify the effort','too easy to try','not allowed']]].map(x=>({prompt:x[0],options:x[2],correct:x[1]}));
 return `<section class="lesson-section read-section guided-reading" data-section-panel="read"><div class="section-heading"><span>35–38 min</span><h2>Reading Journey</h2></div><aside class="book-note reading-intro"><div>📖 <strong>Spotlight 8 · Module 1a · Reading & Vocabulary · p.10</strong><br>Read one paragraph, think, check, then continue.</div><img src="assets/lesson-1/reading-note.png" alt="Kate reading and thinking about vocabulary" loading="lazy"></aside>
 <div class="reading-progress" aria-label="Reading progress"><strong>Paragraph <span class="current-read-number">${state.answers.l1_read_step||1}</span> of 8</strong><div>${Array.from({length:8},(_,i)=>`<i data-read-segment="${i+1}"></i>`).join('')}</div><small class="article-read-status">${Number(state.answers.l1_read_step)>=8?'Article read ✓':'READ → THINK → CHECK → CONTINUE'}</small></div>
 <article class="task journal-task pre-reading">${core}<span class="task-number">EXERCISE 1 · BEFORE READING</span><h2>BREAKING THE ICE</h2>${mc('l1_pre_read','What do you think “break the ice” means?','Do not reveal the answer before choosing.',[{prompt:'Choose the meaning.',options:['break something made of ice','make people feel more relaxed when they first meet','stop talking to somebody','become angry with somebody'],correct:'make people feel more relaxed when they first meet'}])}<aside class="one-to-one-prompt"><strong>🗣 TALK TO YOUR TEACHER</strong><p>How would you start a conversation with someone you don't know?</p><small>I could say… · I could ask…</small></aside><button class="btn primary jump-reading" data-next-read="1">Read and check →</button></article>
 <div class="reading-journey">
 ${card(1,'THE PROBLEM','',p1,`<div class="multi-check" data-multi="l1_r1_problem" data-correct="The person suddenly doesn’t know what to say.|The person feels nervous and uncomfortable." data-max="2"><h3>What happens when the opportunity to speak comes up? Choose TWO.</h3>${['The person wants to talk to someone.','The person suddenly doesn’t know what to say.','The other person walks away.','The person feels nervous and uncomfortable.','The person doesn’t like meeting new people.'].map(x=>chip('l1_r1_problem',x,x,2)).join('')}<button class="btn check-guide-multi">Check</button><p class="feedback"></p></div><div class="multi-check" data-multi="l1_r1_signs" data-correct="palms sweat|blush|look away" data-max="3"><h3>Which details show nervousness?</h3>${['palms sweat','blush','look away','smile confidently','talk a lot'].map(x=>chip('l1_r1_signs',x,x,3)).join('')}<button class="btn check-guide-multi">Check</button><p class="feedback"></p></div><aside class="one-to-one-prompt"><strong>🗣 TALK TO YOUR TEACHER</strong><p>Have you ever wanted to speak but couldn't think what to say?</p><small>Yes · No · Sometimes. A fictional example is fine.</small></aside>`,2)}
 ${card(2,'WHAT DOES “BREAK THE ICE” MEAN?','',p2,`<div class="idea-flow"><b>SITUATION</b><span>You don't know the person very well.</span><i>↓</i><b>FEELING</b><select data-guide-answer="shy / uncomfortable"><option>Choose…</option><option>shy / uncomfortable</option><option>angry</option><option>bored</option></select><i>↓</i><b>ACTION</b><span>say or do something</span><i>↓</i><b>GOAL</b><select data-guide-answer="start a friendly conversation"><option>Choose…</option><option>start a friendly conversation</option><option>end the conversation</option><option>avoid the person</option></select><button class="btn check-guide-selects" data-store="l1_r2_flow">Check</button><p class="feedback"></p></div>${mc('l1_r2_react','Word in context','What does “react” mean here?',[{prompt:"You don't know how the other person will react.",options:['what they will do or say in response','what they look like','where they will go'],correct:'what they will do or say in response'}])}`,3)}
 ${card(3,"YOU'RE NOT THE ONLY ONE",'',p3,`${mc('l1_r3_message','Main message','Why does the writer include this paragraph?',[{prompt:'Choose one.',options:['to tell the reader that the problem is unusual','to reassure the reader before giving advice','to tell a funny story','to explain why people dislike each other'],correct:'to reassure the reader before giving advice'}])}<div class="transition-strip">PROBLEM → REASSURANCE → ADVICE</div>`,4,'Ready for the tips? →')}
 ${card(4,'TIP 1 — SMILE','🙂',p4,`<div class="smile-order"><h3>Put the effect chain in order</h3>${(state.choices.l1_smile_order||['They may smile back.','You smile.','Starting the conversation feels easier.','The other person thinks you look friendly.']).map((x,i)=>`<div data-order-index="${i}"><span>${x}</span><button class="move-smile" data-dir="-1">↑</button><button class="move-smile" data-dir="1">↓</button></div>`).join('')}<button class="btn check-smile-order">Check order</button><p class="feedback"></p></div>${mc('l1_r4_finish','Finish the tip','Smile because it can make the situation feel…',[{prompt:'Choose one.',options:['more comfortable','more serious','more formal'],correct:'more comfortable'}])}<p class="tip-note">💡 Smiling does not guarantee a good reaction. It is simply one way to make starting a conversation easier.</p>`,5,'Next tip →')}
 ${card(5,'TIP 2 — DEVELOP PASSIONS','🎨',p5,`${mc('l1_r5_profile','Who has something to add?','Choose the easiest starting point for an interesting conversation.',[{prompt:"Mia: “I don't really do anything.” · Leo: “I play basketball, learn guitar and love films.” · Sam: “I only ask questions.”",options:['Mia','Leo','Sam'],correct:'Leo'},{prompt:'Why?',options:['He has interests he can talk about.','He talks more loudly.','He knows more people.'],correct:'He has interests he can talk about.'}])}<aside class="one-to-one-prompt"><strong>🗣 TALK TO YOUR TEACHER</strong><p>Choose ONE thing you enjoy.</p><small>I'm really into… · I enjoy…</small></aside>`,6,'Next tip →')}
 ${card(6,'TIP 3 — BE POSITIVE','☀️',p6,`<div class="multi-check" data-multi="l1_r6_advice" data-correct="look for something positive|be confident|try to share positive energy" data-max="3"><h3>What does the writer recommend? Select THREE.</h3>${['look for something positive','complain about everything','be confident','try to share positive energy','pretend that problems never exist','make yourself look perfect'].map(x=>chip('l1_r6_advice',x,x,3)).join('')}<button class="btn check-guide-multi">Check</button><p class="feedback"></p></div>${mc('l1_r6_bright','Look on the bright side','What does the expression mean?',[{prompt:'Choose one.',options:['look at something bright','try to notice the positive part of a situation','ignore everybody around you'],correct:'try to notice the positive part of a situation'},{prompt:'Which advice is closer?',options:['Never have negative feelings.','Try not to focus only on negative things.'],correct:'Try not to focus only on negative things.'}])}`,7,'Next tip →')}
 ${card(7,'TIP 4 — BE A GOOD LISTENER','👂',p7,`<div class="listener-sort">${[['asks the other person questions','GOOD LISTENER'],['talks only about themselves','TAKES OVER'],['listens to the answer','GOOD LISTENER'],['changes every topic back to themselves','TAKES OVER'],['shows interest in the other person','GOOD LISTENER']].map((x,i)=>`<label>${x[0]}<select data-listener="${i}" data-answer="${x[1]}"><option>Choose…</option><option>GOOD LISTENER</option><option>TAKES OVER</option></select></label>`).join('')}<button class="btn check-listener">Check</button><p class="feedback"></p></div><figure class="conversation-reading-visual reading-insert editorial-image"><img src="assets/lesson-1/conversation-emma-kate.png" alt="Two teenagers listening and responding during a conversation" loading="lazy"><figcaption>Listen. React. Ask.</figcaption></figure>${mc('l1_r7_dialogue','Micro dialogue','Which response shows better listening?',[{prompt:'A: I love basketball.',options:["Version A: I love basketball too. I play every day. I'm really good at it. I also…",'Version B: Really? How often do you play?'],correct:'Version B: Really? How often do you play?'}])}<p class="tip-note">A good conversation needs both talking AND listening.</p>`,8,'Final tip →')}
 ${card(8,'TIP 5 — GET OUT THERE','🚪',p8,`${mc('l1_r8_final','What is the final message?','What does the writer want you to do?',[{prompt:'Choose one.',options:['wait until you never feel nervous','avoid people who seem shy','give yourself opportunities to meet and talk to people','always wait for the other person to speak first'],correct:'give yourself opportunities to meet and talk to people'},{prompt:'Why might the other person not start?',options:['They may be shy too.','They dislike you.','They have nothing to say.'],correct:'They may be shy too.'}])}<div class="cause-result"><p>If you avoid every uncomfortable situation… <b>you don't get much practice.</b></p><p>If you stay in the situation… <b>you may gradually get used to it.</b></p></div><p class="tip-note">Sometimes both people are waiting for the other person to break the ice.</p>`,9,'Check the whole text →')}
 </div><section class="reading-recap" data-read-step="9"><h2>Article read ✓</h2><p>What did the article recommend?</p><div><span>🙂 Smile</span><span>🎨 Develop passions</span><span>☀️ Be positive</span><span>👂 Be a good listener</span><span>🚪 Get out there</span></div></section>
 <article class="task journal-task tfd-task">${core}<span class="task-number">EXERCISE 2</span><h2>True, False or Doesn't Say?</h2><p><b>FALSE:</b> the text gives different information. <b>DOESN'T SAY:</b> the text does not give enough information.</p>${tfd.map((x,i)=>`<div class="tfd-row" data-correct="${x[1]}"><p><b>${i+1}.</b> ${x[0]}</p><div>${['T','F','DS'].map(o=>`<button class="choice ${state.choices.l1_spotlight_tfd?.[i]===o?'selected':''}" data-tfd="${i}" data-value="${o}">${o}</button>`).join('')}</div>${[3,5,6].includes(i)?`<label class="false-correction ${state.choices.l1_spotlight_tfd?.[i]==='F'?'':'is-hidden'}">Correct the statement.<input id="l1_correction_${i}" value="${saved(`l1_correction_${i}`)}" placeholder="${esc(corrections[i])}"></label>`:''}</div>`).join('')}<button class="btn primary check-tfd">Check all</button><p class="feedback">${state.scores.l1_spotlight_tfd!==undefined?`Score: ${state.scores.l1_spotlight_tfd}/7`:''}</p></article>
 ${mc('l1_word_detective','Word Detective','Explain the words in bold. Guess from context before checking.',words).replace('>',`>${core}`)}
 <article class="task journal-task study-skills"><span class="task-number">STUDY SKILLS</span><h2>How to read effectively</h2><p>An author's purpose is the reason they wrote the text. Common purposes include:</p><div><span>entertain</span><span>persuade</span><span>inform</span><span>advise</span><span>describe</span><span>narrate</span></div><p>Recognising the author's purpose can help you understand the text better.</p></article>
 ${mc('l1_spotlight_purpose','Why did the author write this article?','Choose the author’s purpose.',[{prompt:'Choose the purpose.',options:['to tell a funny story','to describe a school','to advise readers about meeting new people','to advertise a social club'],correct:'to advise readers about meeting new people'}]).replace('<article','<article data-spotlight-purpose="true"').replace('<span class="task-number">TASK </span>',`${core}<span class="task-number">EXERCISE 3</span>`)}<div class="multi-check purpose-evidence" data-multi="l1_purpose_evidence" data-correct="the five tips|instructions such as “Smile” and “Be a good listener”|advice about what to do" data-max="3"><h3>Which parts of the text helped you decide?</h3>${['the five tips','instructions such as “Smile” and “Be a good listener”','advice about what to do','the photograph only'].map(x=>chip('l1_purpose_evidence',x,x,3)).join('')}<button class="btn check-guide-multi">Check</button><p class="feedback"></p></div>
 <aside class="one-to-one-prompt reading-discussion"><strong>🗣 TALK TO YOUR TEACHER</strong><p>Which TWO tips are most useful? Why?</p><small>I think ___ is useful because… · For me, ___ is more useful than ___ because…</small><p>Teacher: Which tip would be easiest? Which might be difficult?</p></aside>
 <article class="task journal-task article-notes"><span class="task-number">OPTIONAL · THE ARTICLE IN 6 NOTES</span><h2>One short note for each idea</h2>${[['problem','The problem'],['smile','Smile'],['passions','Develop passions'],['positive','Be positive'],['listener','Be a good listener'],['out','Get out there']].map(x=>`<label>${x[1]}<input id="l1_note_${x[0]}" value="${saved(`l1_note_${x[0]}`)}" placeholder="one short note"></label>`).join('')}<button class="btn save-reading-notes">Save notes</button><p class="feedback"></p></article>
 <div class="section-nav"><button class="btn next-section" data-go="warm">← Previous</button><button class="btn next-section" data-go="words">Next: Word Hunt →</button></div></section>`;
}

function bindLessonOneGuidedReading(){
 const current=Math.max(1,Number(state.answers.l1_read_step)||1),steps=[...app.querySelectorAll('[data-read-step]')];
 const refresh=n=>{state.answers.l1_read_step=Math.max(Number(state.answers.l1_read_step)||1,n);saveState();app.querySelector('.current-read-number').textContent=Math.min(n,8);app.querySelectorAll('[data-read-segment]').forEach(x=>x.classList.toggle('done',Number(x.dataset.readSegment)<=Math.min(state.answers.l1_read_step,8)));steps.forEach(x=>{x.classList.toggle('read-active',Number(x.dataset.readStep)===n);x.classList.toggle('read-complete',Number(x.dataset.readStep)<state.answers.l1_read_step)});if(n>=8)app.querySelector('.article-read-status').textContent='Article read ✓'};
 refresh(current);app.querySelectorAll('.idea-flow select').forEach((s,i)=>s.value=state.choices.l1_r2_flow?.[i]||'Choose…');app.querySelectorAll('[data-next-read]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.nextRead);refresh(n);app.querySelector(`[data-read-step="${n}"]`)?.scrollIntoView({behavior:'smooth',block:'start'})});
 app.querySelectorAll('.check-guide-multi').forEach(b=>b.onclick=()=>{const box=b.closest('.multi-check'),chosen=state.choices[box.dataset.multi]||[],correct=box.dataset.correct.split('|'),ok=chosen.length===correct.length&&correct.every(x=>chosen.includes(x));state.scores[box.dataset.multi]=chosen.filter(x=>correct.includes(x)).length;saveState();b.nextElementSibling.textContent=ok?(box.dataset.multi==='l1_r1_signs'?'Correct ✓ These are physical signs that someone may feel nervous.':'Correct ✓'):`You found ${state.scores[box.dataset.multi]} correct idea(s). Try again.`});
 app.querySelectorAll('.check-guide-selects').forEach(b=>b.onclick=()=>{const box=b.closest('.idea-flow'),selects=[...box.querySelectorAll('select')],vals=selects.map(x=>x.value),score=selects.filter(x=>x.value===x.dataset.guideAnswer).length;state.choices[b.dataset.store]=vals;state.scores[b.dataset.store]=score;saveState();b.nextElementSibling.textContent=score===2?'Correct ✓ break the ice = make a first meeting easier and more relaxed.':`${score}/2 correct.`});
 const smile=app.querySelector('.smile-order');app.querySelectorAll('.move-smile').forEach(b=>b.onclick=()=>{const rows=[...smile.querySelectorAll('[data-order-index]')],i=Number(b.closest('[data-order-index]').dataset.orderIndex),j=i+Number(b.dataset.dir);if(j<0||j>=rows.length)return;const order=rows.map(x=>x.querySelector('span').textContent);[order[i],order[j]]=[order[j],order[i]];state.choices.l1_smile_order=order;saveState();render()});app.querySelector('.check-smile-order')?.addEventListener('click',e=>{const order=[...smile.querySelectorAll('[data-order-index] span')].map(x=>x.textContent),correct=['You smile.','The other person thinks you look friendly.','They may smile back.','Starting the conversation feels easier.'];state.scores.l1_smile_order=order.every((x,i)=>x===correct[i])?4:0;saveState();e.currentTarget.nextElementSibling.textContent=state.scores.l1_smile_order?'Correct: A → B → C → D ✓':'Not yet. What happens first?'});
 app.querySelector('.check-listener')?.addEventListener('click',e=>{const selects=[...app.querySelectorAll('[data-listener]')],score=selects.filter(x=>x.value===x.dataset.answer).length;state.choices.l1_listener=selects.map(x=>x.value);state.scores.l1_listener=score;saveState();e.currentTarget.nextElementSibling.textContent=`${score}/5 correct.`});app.querySelectorAll('[data-listener]').forEach((x,i)=>x.value=state.choices.l1_listener?.[i]||'Choose…');
 app.querySelectorAll('[data-tfd]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.tfd);state.choices.l1_spotlight_tfd=state.choices.l1_spotlight_tfd||[];state.choices.l1_spotlight_tfd[i]=b.dataset.value;b.closest('.tfd-row').querySelectorAll('.choice').forEach(x=>x.classList.toggle('selected',x===b));b.closest('.tfd-row').querySelector('.false-correction')?.classList.toggle('is-hidden',b.dataset.value!=='F');saveState()});
 app.querySelector('.check-tfd')?.addEventListener('click',e=>{let score=0;app.querySelectorAll('.tfd-row').forEach((row,i)=>{const selected=state.choices.l1_spotlight_tfd?.[i];if(selected===row.dataset.correct)score++;row.classList.toggle('correct',selected===row.dataset.correct);row.classList.toggle('incorrect',!!selected&&selected!==row.dataset.correct);const input=row.querySelector('.false-correction input');if(input)state.answers[input.id]=input.value.trim()});state.scores.l1_spotlight_tfd=score;saveState();e.currentTarget.nextElementSibling.textContent=`Score: ${score}/7. You can correct false statements and retry.`});
 app.querySelector('.save-reading-notes')?.addEventListener('click',e=>{app.querySelectorAll('[id^="l1_note_"]').forEach(x=>state.answers[x.id]=x.value.trim());saveState();e.currentTarget.nextElementSibling.textContent='Notes saved ✓'});
}
